package governance

// Evidence is a structured record of governance evaluation for audit and tracing.
// It is a VALUE type — no pointers, no interfaces, fully JSON-serialisable.
// Attach to trace events as structured metadata.
type Evidence struct {
	// EvaluatedAt is the RFC3339 timestamp of when evaluation occurred.
	EvaluatedAt string `json:"evaluated_at"`

	// StepID is the step that was evaluated.
	StepID string `json:"step_id"`

	// PolicyApplied describes the policy source (e.g., "runbook:governance", "merged:runbook+step").
	PolicyApplied string `json:"policy_applied"`

	// RulesEvaluated is the total count of rules checked.
	RulesEvaluated int `json:"rules_evaluated"`

	// RulesMatched lists every rule that produced a match.
	RulesMatched []MatchedRule `json:"rules_matched"`

	// Outcome is "allowed", "denied", or "approval_required".
	Outcome string `json:"outcome"`

	// DenyReason is set when Outcome == "denied".
	DenyReason string `json:"deny_reason,omitempty"`

	// ApprovalRecord is set when approval was requested and received.
	ApprovalRecord *ApprovalRecord `json:"approval_record,omitempty"`

	// BlockedEnvVars lists env var names stripped from the step's environment.
	BlockedEnvVars []string `json:"blocked_env_vars,omitempty"`

	// RedactionsApplied is the count of redaction patterns that matched output.
	// Set during post-execution redaction pass, not during pre-flight.
	RedactionsApplied int `json:"redactions_applied"`
}

// ApprovalRecord is the result of an approval gate decision.
// Value type, JSON-serialisable, suitable for embedding in Evidence and trace events.
type ApprovalRecord struct {
	// Approver is the identity of the person who approved (e.g., "alice-id").
	Approver string `json:"approver"`

	// ApprovedAt is the RFC3339 timestamp of the approval decision.
	ApprovedAt string `json:"approved_at"`

	// Token is an opaque string for audit trail correlation.
	// Generated by the ApprovalGate implementation (e.g., UUID).
	Token string `json:"token"`
}
